# Generated by Django 4.2.8 on 2025-11-22 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_imagenbase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='casa',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='casa',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='imagencasa',
            name='imagen_base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.imagenbase', verbose_name='Imagen de la galería'),
            preserve_default=False,
        ),
    ]
