# Generated by Django 4.2.8 on 2025-11-22 22:00

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_casa_codigo_postal_casa_estado_casa_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='banos',
            field=models.IntegerField(blank=True, help_text='Número de baños', null=True, validators=[web.models.validar_banos_positivos]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal de 5 dígitos', max_length=10, null=True, validators=[web.models.validar_codigo_postal], verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la propiedad', null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección completa de la propiedad', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado donde se encuentra la propiedad', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='habitaciones',
            field=models.IntegerField(blank=True, help_text='Número de habitaciones', null=True, validators=[web.models.validar_habitaciones_positivas]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de latitud (-90 a 90)', max_digits=10, null=True, validators=[web.models.validar_latitud]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de longitud (-180 a 180)', max_digits=11, null=True, validators=[web.models.validar_longitud]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='municipio',
            field=models.CharField(blank=True, help_text='Municipio donde se encuentra la propiedad', max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos mexicanos', max_digits=10, validators=[web.models.validar_precio_positivo]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='superficie_m2',
            field=models.IntegerField(blank=True, help_text='Superficie en metros cuadrados', null=True, validators=[web.models.validar_superficie_positiva]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='titulo',
            field=models.CharField(help_text='Título descriptivo de la propiedad', max_length=255),
        ),
    ]
