"""
Django settings for multicasa_proyecto project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wu4dag^ahv^+$!o5bi*5s0$%g!i8+alt08&5&0*0ptrjq5o&8t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'web.apps.WebConfig',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'multicasa_proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # <-- Esta es la línea clave
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'multicasa_proyecto.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'multicasa',  # El nombre de la BD que creamos
        'USER': 'Alfonso',  # Tu usuario de MySQL (ej. 'root')
        'PASSWORD': 'Alfonso1',  # Tu contraseña de MySQL
        'HOST': 'localhost',  # O la IP si el servidor está en otro lado
        'PORT': '3306',  # Puerto por defecto de MySQL
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------------------------------------------
# Configuración de Email (Modo Desarrollo)
# -----------------------------------------------------------------
# Configuración de Email para Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'contactomulticasa@gmail.com'  # Cambia por tu email real
EMAIL_HOST_PASSWORD = 'viwo ozig hkss vxpz'  # ← PASO IMPORTANTE
DEFAULT_FROM_EMAIL = 'contactomulticasa@gmail.com'  # Mismo que EMAIL_HOST_USER
# -----------------------------------------------------------------

# =========================
# CONFIGURACIÓN DE SEGURIDAD Y SESIONES
# =========================

# 1. Hace que la sesión expire al cerrar el navegador.
# Nota: Esto generalmente aplica al cerrar TODA la ventana del navegador, no solo una pestaña.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 2. Define un tiempo máximo de vida de la sesión en segundos (ej. 30 minutos).
# Si el admin deja el panel abierto y se va, se desconectará automáticamente tras este tiempo.
SESSION_COOKIE_AGE = 1800  # 1800 segundos = 30 minutos

# 3. (Opcional) Refresca la duración de la sesión con cada clic.
# Esto evita que se le cierre la sesión a alguien que está trabajando activamente.
SESSION_SAVE_EVERY_REQUEST = True
